logging:
  level:
    com.teoresi.staff: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  flyway:
    enabled: false
  sql:
    init:
      mode: never
      platform: h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/h2/staff/staff-be
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
          format_sql: true
          show_sql: ture
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
application:
  cors:
    allowedOrigins: 'http://localhost:4200'

