logging:
  level:
    com.client.staff: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: logfile.log
    path: classpath


spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db
    username: root
    password: root

    jpa:
    properties:
      hibernate:
        ddl :
          auto : validate
          format_sql: true

  flyway:
    enabled: false
    baselineOnMigrate: true
    validateOnMigrate: true
    locations:
      - classpath:mysql/schema
      - classpath:mysql/prod-data

application:
  cors:
    allowedOrigins: 'http://localhost:4200'