server:
  port: 8080
  error:
    include-message: always
spring:

  application:
    name: @project.name@
    version: @project.version@

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: fraquinta@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: true
    time-zone: UTC
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Rome

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  jwt:
    secretKey: Njs3Qodn8JDndpwm
    cryptoKey: Qs23RBNF330ms00n

    tokenDurationMs: 1800000
    tokenRenewBeforeExpirationMs: 1800000
